version: '3.5'
services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
     - POSTGRES_USER=api
     - POSTGRES_PASSWORD=api
     - POSTGRES_DB=laravel
     - PGDATA=/var/lib/postgresql/data
    volumes:
      - star_wars_api_data:/var/lib/postgresql/data


  api:
    image: "ilozulu_chris_sw_api:latest"
    restart: always
    depends_on:
      - db
    environment:
      - PORT=8181
    ports:
      - "8181:8181"

volumes:
  star_wars_api_data:
    external: true
