version: '3.5'
services:
  db:
    image: "postgres:12"
    restart: always
    environment:
     - POSTGRES_USER=api
     - POSTGRES_PASSWORD=api
     - POSTGRES_DB=laravel
     - PGDATA=/var/lib/postgresql/data
    volumes:
      - star_wars_api_data:/var/lib/postgresql/data


  api:
    image: "ilozulu_chris_sw_api:latest"
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - PORT=8181
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:t9zlqPFdHDipViU69I8q/jq0EzPTyz6o2Mo7mPV54fg=
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=api
      - DB_PASSWORD=api
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - L5_SWAGGER_GENERATE_ALWAYS=true
    ports:
      - "8181:8181"
  redis:
    image: "redis:5.0.6"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - cache_data:/data


volumes:
  star_wars_api_data:
    external: true
  cache_data:
    external: true
